from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/', views.login, name="login"),
    url(r'logout/', views.logout, name="logout"),
    # url(r'create/', views.create, name="create"),
    url(r'create_scanner/', views.create_scanner, name="create_scanner"),
    url(r'scanner_list/', views.scanner_list, name="scanner_list"),
    url(r'scanner_list_api/', views.scanner_list_api, name="scanner_list_api"),
    url(r'scanner/(?P<ID>[\S]*)', views.scanner, name="scanner"),
    url(r'scanner_oper/', views.scanner_oper, name="scanner_oper"),
    url(r'scanner_update/', views.scanner_update, name="scanner_update"),
    url(r'search_log/', views.search_log, name="search_log"),
    url(r'search_log_api/', views.search_log_api, name="search_log_api"),
    url(r'search_log_del/', views.deletelog, name="search_log_del"),
    url(r'zmap_scan_task/', views.zmap_scan_task, name="zmap_scan_task"),
    url(r'create_zmap_task/', views.create_zmap_scan_task, name="create_zmap_task"),
    url(r'nmap_scan_task/', views.nmap_scan_task, name="nmap_scan_task"),
    url(r'create_nmap_task/', views.create_nmap_scan_task, name="create_nmap_task"),
    url(r'scan_task_list/', views.scan_task_list, name="scan_task_list"),
    url(r'get_task_detail/', views.get_task_detail, name="get_task_detail"),
    url(r'poc/', views.poc, name="poc"),
    url(r'poc_edit/', views.poc_edit, name="poc_edit"),
    url(r'poc_del/', views.poc_delete, name="poc_del"),
    url(r'poc_run/', views.poc_run, name="poc_run"),
    url(r'poc_list/', views.poc_list, name="poc_list"),
    url(r'poc_detail/', views.poc_detail, name="poc_detail"),
    url(r'product/', views.product, name="product"),
    url(r'product_add/', views.add_product, name="product_add"),
    url(r'product_list/', views.product_list, name="product_list"),
    url(r'product_edit/', views.product_edit, name="product_edit"),
    url(r'product_update/', views.product_update, name="product_update"),
    url(r'vul_add/', views.add_vul_type, name="vul_add"),

]
