# Generated by Django 2.1.7 on 2019-02-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField(max_length=200)),
                ('dst_port', models.IntegerField()),
                ('src_port', models.IntegerField()),
                ('subnets', models.CharField(max_length=20)),
                ('network_card', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('progress_rate', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('scanner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scanner_token', models.CharField(max_length=24)),
                ('scanner_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('scanner_port', models.IntegerField()),
                ('scanner_date', models.DateTimeField(auto_now=True)),
                ('scanner_status', models.IntegerField(choices=[(0, 'shutdown'), (1, 'runing'), (2, 'unable to connect')])),
                ('scanner_es_hosts', models.TextField()),
                ('scanner_es_port', models.IntegerField()),
                ('scanner_es_user', models.CharField(max_length=10)),
                ('scanner_es_pass', models.CharField(max_length=64)),
                ('scanner_borker_type', models.CharField(choices=[('redis', 'redis'), ('amqp', 'amqp')], max_length=5)),
                ('scanner_borker_user', models.CharField(max_length=10)),
                ('scanner_borker_pass', models.CharField(max_length=64)),
                ('scanner_borker_host', models.GenericIPAddressField(protocol='ipv4')),
                ('scanner_borker_port', models.IntegerField()),
                ('scanner_borker_db', models.CharField(max_length=10)),
                ('scanner_backend_type', models.CharField(choices=[('redis', 'redis'), ('amqp', 'amqp')], max_length=5)),
                ('scanner_backend_user', models.CharField(max_length=10)),
                ('scanner_backend_pass', models.CharField(max_length=64)),
                ('scanner_backend_host', models.GenericIPAddressField(protocol='ipv4')),
                ('scanner_backend_port', models.IntegerField()),
                ('scanner_backend_db', models.CharField(max_length=10)),
            ],
        ),
    ]
