# Generated by Django 2.0.4 on 2018-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField(max_length=200)),
                ('dst_port', models.IntegerField()),
                ('src_port', models.IntegerField()),
                ('subnets', models.CharField(max_length=20)),
                ('network_card', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('progress_rate', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
