# Generated by Django 2.1.7 on 2019-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('scanner_token', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('scanner_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('scanner_port', models.IntegerField()),
                ('scanner_date', models.DateTimeField(auto_now=True)),
                ('scanner_status', models.IntegerField(choices=[(0, 'shutdown'), (1, 'runing'), (2, 'not install yet')])),
                ('scanner_es_hosts', models.TextField()),
                ('scanner_es_port', models.IntegerField()),
                ('scanner_es_user', models.CharField(max_length=10)),
                ('scanner_es_pass', models.CharField(max_length=64)),
                ('scanner_borker_type', models.CharField(choices=[('redis', 'redis'), ('amqp', 'amqp')], max_length=5)),
                ('scanner_borker_user', models.CharField(max_length=10)),
                ('scanner_borker_pass', models.CharField(max_length=64)),
                ('scanner_borker_host', models.GenericIPAddressField(protocol='ipv4')),
                ('scanner_borker_port', models.IntegerField()),
                ('scanner_borker_db', models.CharField(max_length=10)),
                ('scanner_backend_type', models.CharField(choices=[('redis', 'redis'), ('amqp', 'amqp')], max_length=5)),
                ('scanner_backend_user', models.CharField(max_length=10)),
                ('scanner_backend_pass', models.CharField(max_length=64)),
                ('scanner_backend_host', models.GenericIPAddressField(protocol='ipv4')),
                ('scanner_backend_port', models.IntegerField()),
                ('scanner_backend_db', models.CharField(max_length=10)),
            ],
        ),
    ]
