# Generated by Django 2.1.7 on 2019-03-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('searcher_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('searcher_IP', models.GenericIPAddressField(protocol='ipv4')),
                ('searcher_date', models.DateTimeField(auto_now=True)),
                ('searcher_content', models.TextField()),
            ],
            options={
                'ordering': ['-searcher_ID'],
            },
        ),
    ]
