# Generated by Django 2.1.7 on 2019-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searcher_IP', models.GenericIPAddressField(protocol='ipv4')),
                ('searcher_date', models.DateTimeField(auto_now=True)),
                ('searcher_content', models.TextField()),
            ],
        ),
    ]
